"use client";

import { useEffect } from "react";
import { FiDownload, FiX } from "react-icons/fi";
import { formatFileSize } from "./document-type-options";
import type { StudentDocumentListItemDTO } from "@/modules/students/application/dto/student-document.dto";

interface StudentDocumentPreviewProps {
  document: StudentDocumentListItemDTO;
  onClose: () => void;
}

// Image Preview / PDF Preview / Download. Uses the signed URL already generated by
// ListStudentDocumentsService — never fetches or constructs a storage URL itself.
export function StudentDocumentPreview({ document, onClose }: StudentDocumentPreviewProps) {
  useEffect(() => {
    function handleEscape(event: KeyboardEvent) {
      if (event.key === "Escape") onClose();
    }
    window.addEventListener("keydown", handleEscape);
    return () => window.removeEventListener("keydown", handleEscape);
  }, [onClose]);

  const isImage = document.mimeType.startsWith("image/");
  const isPdf = document.mimeType === "application/pdf";

  return (
    <div
      role="dialog"
      aria-modal="true"
      aria-label={`Preview of ${document.originalFileName}`}
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"
      onClick={onClose}
    >
      <div
        className="flex max-h-[85vh] w-full max-w-3xl flex-col overflow-hidden rounded-xl bg-white shadow-xl"
        onClick={(event) => event.stopPropagation()}
      >
        <div className="flex items-center justify-between border-b border-zinc-200 px-4 py-3">
          <div className="min-w-0">
            <p className="truncate text-sm font-medium text-zinc-900">{document.originalFileName}</p>
            <p className="text-xs text-zinc-500">{formatFileSize(document.fileSize)}</p>
          </div>
          <div className="flex items-center gap-3">
            <a
              href={document.signedUrl}
              download={document.originalFileName}
              className="flex items-center gap-1 rounded-lg border border-zinc-300 px-3 py-1.5 text-sm font-medium text-zinc-700 hover:border-zinc-400"
            >
              <FiDownload className="h-4 w-4" /> Download
            </a>
            <button
              type="button"
              onClick={onClose}
              aria-label="Close preview"
              className="text-zinc-400 hover:text-zinc-600"
            >
              <FiX className="h-5 w-5" />
            </button>
          </div>
        </div>

        <div className="flex flex-1 items-center justify-center overflow-auto bg-zinc-50 p-4">
          {isImage && (
            // eslint-disable-next-line @next/next/no-img-element -- signed URL from Supabase Storage, not a static/optimizable local asset.
            <img
              src={document.signedUrl}
              alt={document.originalFileName}
              className="max-h-[65vh] max-w-full rounded-lg object-contain"
            />
          )}
          {isPdf && (
            <iframe
              src={document.signedUrl}
              title={document.originalFileName}
              className="h-[65vh] w-full rounded-lg border border-zinc-200 bg-white"
            />
          )}
          {!isImage && !isPdf && (
            <p className="py-12 text-sm text-zinc-500">
              No inline preview available for this file type — use Download instead.
            </p>
          )}
        </div>
      </div>
    </div>
  );
}
