"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { uploadEmployeeDocumentAction, deleteEmployeeDocumentAction } from "@/app/hr/actions";
import { Card } from "@/components/ui/Card";
import { FormField } from "@/components/ui/FormField";
import { Select } from "@/components/ui/Select";
import type { EmployeeDocumentListItemDTO, UploadableEmployeeDocumentType } from "@/modules/hr/application/dto/employee-document.dto";

interface DocumentsTabProps {
  employeeId: string;
  documents: EmployeeDocumentListItemDTO[];
  canManage: boolean;
}

// The 6 upload-only document types a user may attach as a file — deliberately excludes OTHER
// (schema-level UploadableEmployeeDocumentType allows it, but this dropdown is scoped to exactly
// the 6 named categories) and every letter/certificate type (those are system-generated by a
// separate letter-generation feature, not uploaded here).
const UPLOADABLE_DOCUMENT_TYPES: UploadableEmployeeDocumentType[] = [
  "PHOTO",
  "RESUME",
  "IDENTITY_PROOF",
  "BANK_PROOF",
  "MEDICAL_CERTIFICATE",
  "POLICE_VERIFICATION",
];

const DOCUMENT_TYPE_LABELS: Record<string, string> = {
  PHOTO: "Photo",
  RESUME: "Resume",
  IDENTITY_PROOF: "Identity Proof",
  BANK_PROOF: "Bank Proof",
  MEDICAL_CERTIFICATE: "Medical Certificate",
  POLICE_VERIFICATION: "Police Verification",
  APPOINTMENT_LETTER: "Appointment Letter",
  JOINING_LETTER: "Joining Letter",
  PROMOTION_LETTER: "Promotion Letter",
  WARNING_LETTER: "Warning Letter",
  EXPERIENCE_CERTIFICATE: "Experience Certificate",
  RELIEVING_LETTER: "Relieving Letter",
  OTHER: "Other",
};

function formatFileSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

// Unified list of both uploaded documents and system-generated letters/certificates (the same
// `documentType` vocabulary covers both, per modules/hr/domain/employee-document.entity.ts) —
// generated letters simply appear here once the separate letter-generation feature starts
// creating them; this tab does not build that generation UI itself. Download resolves through
// `signedUrl`, already present on EmployeeDocumentListItemDTO (generated server-side by
// listEmployeeDocuments), mirroring app/students/[studentId]/_components/documents's own
// signed-URL precedent.
export function DocumentsTab({ employeeId, documents, canManage }: DocumentsTabProps) {
  const router = useRouter();
  const [documentType, setDocumentType] = useState<UploadableEmployeeDocumentType>("PHOTO");
  const [isUploading, setIsUploading] = useState(false);
  const [uploadError, setUploadError] = useState<string | null>(null);
  const [deletingId, setDeletingId] = useState<string | null>(null);
  const [rowError, setRowError] = useState<{ id: string; message: string } | null>(null);

  async function handleUpload(event: React.ChangeEvent<HTMLInputElement>) {
    const file = event.target.files?.[0];
    event.target.value = "";
    if (!file) return;

    setIsUploading(true);
    setUploadError(null);
    try {
      const result = await uploadEmployeeDocumentAction({ employeeId, documentType, file });
      if (!result.success) {
        setUploadError(result.error.message);
        return;
      }
      router.refresh();
    } finally {
      setIsUploading(false);
    }
  }

  async function handleDelete(document: EmployeeDocumentListItemDTO) {
    setDeletingId(document.id);
    setRowError(null);
    try {
      const result = await deleteEmployeeDocumentAction(document.id);
      if (!result.success) {
        setRowError({ id: document.id, message: result.error.message });
        return;
      }
      router.refresh();
    } finally {
      setDeletingId(null);
    }
  }

  return (
    <div className="flex flex-col gap-6">
      {canManage && (
        <Card title="Upload Document" description="Photo, resume, identity proof, and other staff records.">
          <div className="flex flex-wrap items-end gap-3">
            <FormField label="Document Type" htmlFor="document-upload-type">
              <Select
                id="document-upload-type"
                value={documentType}
                onChange={(e) => setDocumentType(e.target.value as UploadableEmployeeDocumentType)}
                options={UPLOADABLE_DOCUMENT_TYPES.map((type) => ({ value: type, label: DOCUMENT_TYPE_LABELS[type] ?? type }))}
                className="w-56"
              />
            </FormField>

            <label
              htmlFor="document-upload-file"
              className="cursor-pointer rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-500 aria-disabled:cursor-not-allowed aria-disabled:opacity-60"
              aria-disabled={isUploading}
            >
              {isUploading ? "Uploading…" : "Choose File"}
            </label>
            <input
              id="document-upload-file"
              type="file"
              disabled={isUploading}
              onChange={handleUpload}
              className="hidden"
            />
          </div>

          {uploadError && (
            <p className="mt-3 rounded-lg border border-red-200 bg-red-50 px-4 py-2 text-sm text-red-700">{uploadError}</p>
          )}
        </Card>
      )}

      <Card title="Documents">
        {documents.length === 0 ? (
          <p className="rounded-lg border border-dashed border-zinc-300 bg-zinc-50 px-4 py-6 text-center text-sm text-zinc-500">
            No documents uploaded yet.
          </p>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left text-sm">
              <thead className="border-b border-zinc-200 text-xs uppercase tracking-wide text-zinc-500">
                <tr>
                  <th className="py-2 pr-4">Name</th>
                  <th className="py-2 pr-4">Type</th>
                  <th className="py-2 pr-4">Size</th>
                  <th className="py-2 pr-4">Date</th>
                  <th className="py-2 pr-4 text-right">Actions</th>
                </tr>
              </thead>
              <tbody>
                {documents.map((document) => (
                  <tr key={document.id} className="border-b border-zinc-100 last:border-0">
                    <td className="max-w-[220px] truncate py-2 pr-4 text-zinc-900" title={document.originalFileName}>
                      {document.originalFileName}
                    </td>
                    <td className="py-2 pr-4 text-zinc-600">
                      {DOCUMENT_TYPE_LABELS[document.documentType] ?? document.documentType}
                    </td>
                    <td className="py-2 pr-4 text-zinc-600">{formatFileSize(document.fileSize)}</td>
                    <td className="py-2 pr-4 text-zinc-600">
                      {(document.issuedDate ?? document.createdAt).toLocaleDateString()}
                    </td>
                    <td className="py-2 pr-4">
                      <div className="flex items-center justify-end gap-3">
                        <a
                          href={document.signedUrl}
                          target="_blank"
                          rel="noreferrer"
                          className="text-sm text-blue-600 hover:underline"
                        >
                          Download
                        </a>
                        {canManage && (
                          <button
                            type="button"
                            onClick={() => handleDelete(document)}
                            disabled={deletingId === document.id}
                            className="text-sm text-red-600 hover:underline disabled:opacity-50"
                          >
                            Delete
                          </button>
                        )}
                      </div>
                      {rowError?.id === document.id && (
                        <p className="mt-1 text-right text-xs text-red-600">{rowError.message}</p>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </Card>
    </div>
  );
}
